### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by EmiliosIsaias** [NII-Kobayashi/GLMCC#1]
Hi! 
I am interested in using your method in a set of cortico-subcortical recordings. I was trying to run the commands in Windows 10 and it ran until Est_Data.py that it ran into an issue with the subprocess package. I figured out that this issue is due to incompatibility with Windows10 and tried running it in a Ubuntu virtual machine which seems to work. However, I ran into another issue and it is more into the amount of given data. I saw in the paper that you define the minimum criteria for estimating the connectivity matrix in Table 1 but, unfortunately, our recordings have sparse firing and are maximum 1 hour long. Additionally, I would like to split the experiment into the different treatments that I'm applying, which makes our registered activity even sparser. 

Do you think that I could still use this method for my sparse data?
Do you have a suggestion for running the algorithms in Windows? (I've looked into Cygwin, which is a Linux environment for Windows, but it creates many incompatibilities with my conda environments)

Thank you very much in advance!
Emilio Isaías-Camacho

**Comment by r-koba84** [comment]
Thanks for your inquiry.

> Do you think that I could still use this method for my sparse data?

In general, you can use this method for sparse data. 
The sparser the data is, the more difficult detecting the connectivity is. Note that this issue is independent of the method. 
You can also try our web application just to try!
https://s-shinomoto.com/CONNECT/

> Do you have a suggestion for running the algorithms in Windows? 

Can you tell me more detail? 
For example, how you run the code using conda, the version of the conda and windows, and the error massage.

**Comment by EmiliosIsaias** [comment]
Thank you for your quick reply!
 
I will give it a shot in the web interface, thanks!

I am currently using: 
Windows 10 version 20H2, 
conda 4.9.2, 
python 3.9.2, 
scipy 1.6.1
numpy 1.20.1
matplotlib 3.3.4

The command that I run is 
`python Est_data.py simulation_data 20 sim`

And the error that I get is
![image](https://user-images.githubusercontent.com/12449152/111630079-44bcee80-87f2-11eb-8080-bdaa6150f8cc.png)

Best regards,
Emilio Isaías-Camacho

**Comment by r-koba84** [comment]
Thanks for your reply. 

Please try to change the last lines in the python code "Est_Data.py".

===== before ==================
cmd = ['rm', "J_py_"+str(T)+".txt"]
proc.check_call(cmd)

===== after ==================
import os
os.remove("J_py_"+str(T)+".txt")

I hope it works.

Best regards,
Ryota Kobayashi

**Comment by EmiliosIsaias** [comment]
Thanks a lot for looking into this! 
I'll do the change and test. 
Meanwhile, I've gotten my hands on a Linux system to try out the code and it runs on the simulated data seamlessly! However, as I input my sparse data, the code exits with the following error:
![image](https://user-images.githubusercontent.com/12449152/111764243-4c889b80-88a3-11eb-888a-8022685c9ecb.png)

I reviewed the firing rate of the given cells and the firing rate of the considered one is very low ~0.15 Hz. I've been thinking that maybe a set of bins with 0 counts in the cross correlograms might arise some issues with the logarithm operation. I don't know, what do you think?

Best regards
Emilio Isaías-Camacho

**Comment by r-koba84** [comment]
Thanks for your report. 

I suggest you to exclude the neurons that fires too sparse (< 0.5 Hz). 
I also agree with you that each bin in the cross-correlogram should be more than a spike.

**Comment by EmiliosIsaias** [comment]
Very well, thanks for your time! 
I'll paste here the cross-correlogram of those cells which caused the math domain error in the logarithm sometime later.
